-- create the student table if it does not exist
-- Not Null is used for NAME to ensure every student record has a name
CREATE TABLE IF NOT EXISTS STUDENT (
     ROLL_NO TEXT PRIMARY KEY,
     NAME TEXT NOT NULL,
     ADDRESS TEXT,
     PHONE TEXT,
     AGE INTEGER
);

-- INSERT SAMPLE DATA INTO THE STUDENT TABLE
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'RAM', 'DEHLI', '******', 18),
('2', 'RAMESH', 'GURGOAN', '******', 18),
('3', 'SUJIT', 'ROHTAK', '******', 20),
('4', 'SURESH', 'DEHLI', '******', 18),
('5', 'AMAN', 'ROHTAK', '******', 20),
('6', 'HARSH', 'GURGOAN', '******', 18);

-- SELECT ALL RECORDS FROM THE STUDENT TABLE TO VERIFY INSERTION
SELECT * FROM STUDENT;

-- QUERY STUDENTS WHO ARE 18 YEARS OLD AND LIVE IN DEHLI
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DEHLI';

--QUERY STUDENTS WHO ARE 18 YEARS OLD AND NAMED RAM
SELECT * FROM  STUDENT WHERE AGE = 18 AND NAME = 'RAM';

-- QUERY  STUDENTS NAMED RAM OR SUJIT
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

-- QUERY STUDENTS NAMED RAM OR AGED 20
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;

-- QUERY STUDNETS AGED 18 AND NAMED RAM OR RAMESH
SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME= 'RAM' OR NAME = 'RAMESH');
